//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonPhenomenon.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masters
    {
        public Masters()
        {
            this.Registrations = new HashSet<Registrations>();
        }
    
        public int MasterID { get; set; }
        public string MasterSurname { get; set; }
        public string MasterName { get; set; }
        public string MasterPatronymic { get; set; }
        public int MasterSpecialization { get; set; }

        public string ShortName
        {
            get
            {
                return $"{MasterSurname} {MasterName[0]}.{MasterPatronymic[0]}";
            }
        }
    
        public virtual Specializations Specializations { get; set; }
        public virtual ICollection<Registrations> Registrations { get; set; }
    }
}
