//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonPhenomenon.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registrations
    {
        public int RegistrationID { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.TimeSpan RegistrationTime { get; set; }
        public decimal RegistrationSum { get; set; }
        public string RegSurnameClient { get; set; }
        public string RegNameClient { get; set; }
        public string RegPatronymicClient { get; set; }
        public string RegPhoneNumberClient { get; set; }
        public int RegServiceID { get; set; }
        public int IDStatus { get; set; }
        public int IDMaster { get; set; }
        public string ShortName
        {
            get
            {
                return $"{RegSurnameClient} {RegNameClient[0]}.{RegPatronymicClient[0]}";
            }
        }

        public virtual Masters Masters { get; set; }
        public virtual Services Services { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
