//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonPhenomenon.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        public Services()
        {
            this.Registrations = new HashSet<Registrations>();
        }
    
        public int ServiceID { get; set; }
        public string ServiceName { get; set; }
        public int ServiceDurationInMin { get; set; }
        public decimal ServiceCost { get; set; }
    
        public virtual ICollection<Registrations> Registrations { get; set; }
    }
}
