//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonPhenomenon.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specializations
    {
        public Specializations()
        {
            this.Masters = new HashSet<Masters>();
        }
    
        public int SpecializationID { get; set; }
        public string SpecializationName { get; set; }
    
        public virtual ICollection<Masters> Masters { get; set; }
    }
}
