//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalonPhenomenon.Modules
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
        public int RoleID { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public int FailedAttempts { get; set; }
        public bool IsBlocked { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
